# Generated by Django 3.2.6 on 2022-04-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220409_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='short_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
