# Generated by Django 3.2.6 on 2022-04-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_profile_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.CharField(max_length=255),
        ),
    ]
