# Generated by Django 3.2.6 on 2022-04-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_bid_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('icon', models.ImageField(upload_to='icon')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'NewCategory',
                'verbose_name_plural': 'NewCategorys',
            },
        ),
    ]
