# Generated by Django 3.2.6 on 2022-05-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_newcategory_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='contact_no',
            field=models.CharField(default=0, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='subject',
            field=models.CharField(default=0, max_length=225),
            preserve_default=False,
        ),
    ]
